# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080
  servlet:
    context-path: /znzmo

# Mybatis
mybatis-plus:
  #MyBatis相关自定义配置
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
      #实体类所做包
  type-aliases-package: com.pactera.znzmo.**.
  #mapper.xml所在位置
  mapper-locations: classpath*:**/sqlmap/*.xml

# DataSource
spring:
# 运行环境 dev:开发环境|test:测试环境|prod:生产环境
  profiles:
    active: dev
  # jackson
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://192.168.23.130:3306/znzmo?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      url: jdbc:mysql://192.168.24.53:3306/znzmo?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
#      password: MyPass123!
      password: 123456
      filters: stat,wall,log4j,config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
      

oss:
  endpoint: oss-cn-shenzhen.aliyuncs.com
  accessKeyId: LTAInoyqirMmu6UK
  accessKeySecret: lIGhJF8gtTqNCp3wMQmjaTI6YeqKR
  baseUrl: https://guanyuoss.oss-cn-qingdao.aliyuncs.com/
  bucketname: znzmooss
env: test